sudo: false
language: python
# https://github.com/travis-ci/travis-ci/issues/9815
dist: xenial
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
install: pip install -r dev-requirements.txt
script:
  - tox
  - flake8 sendgrid_backend/
