[tool.poetry]
name = "django-sendgrid-v5"
version = "0.1.0"
description = "This pyproject.toml is only for the dev env"
authors = ["Steven Sklar <sklarsa@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "20.8b1"
codecov = "2.1.10"
coverage = "4.4.1"
flake8 = "3.8.4"
isort = "5.7.0"
jedi = "0.10.2"
mock = "2.0.0"
mypy = "0.920"
nose = "1.3.7"
tox = "3.8.5"
twine = "3.3.0"
typed-ast = "1.5.1"
wheel = "^0.37.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.isort]
profile = "black"
multi_line_output = 3
